version: '2'
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: 123456
        ports:
           - "5671:5671"
           - "5672:5672"
           - "15672:15672"
        volumes:
          - ~/web/rabbitmq:/var/lib/rabbitmq
