version: '2'
services:
    nginx:
        #image: "${DOCKER_USER}/lnmp-nginx:v1.2"
        container_name: nginx_dev
        build:
            context: ./nginx
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
            - "10040:10040"
        volumes:
            - ~/web/conf/nginx/conf.d:/etc/nginx/conf.d
            - ~/web:/web
        networks:
            - frontend
        links:
            - php
        depends_on:
            - php
    php:
        #image: "${DOCKER_USER}/lnmp-php:v1.2"
        container_name: php_dev
        build:
            context: ./php
            dockerfile: Dockerfile.php
        volumes:
            - ~/web:/web
            - ~/web/logs/php:/opt/yrd_logs/php/mock
        networks:
            - frontend
            - backend
        environment:
            MYSQL_PASSWORD: 123456
        depends_on:
            - mysql
            - redis
    mysql:
        container_name: mysql_dev
        image: mysql:5.7
        volumes:
            - ~/web/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: 123456
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
    #redis:
    #    image: 'bitnami/redis:latest'
    #    ports:
    #        - '6379:6379'
    #    environment:
    #        - REDIS_PASSWORD=password123
    #        #- ALLOW_EMPTY_PASSWORD=yes
    #        - REDIS_MASTER_HOST=redis-master
    #    volumes:
    #        - ~/web/redis:/data
    #    networks:
    #        - backend
    redis:
        container_name: redis_dev
        build:
           context: ./redis
           dockerfile: Dockerfile.redis
        ports:
           - "6379:6379"
        volumes:
           - ~/web/redis:/data
        networks:
           - backend
volumes:
    mysql-data:

networks:
    frontend:
    backend:
