version: '2'
services:
    nginx:
        #image: "${DOCKER_USER}/lnmp-nginx:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        volumes:
            - ~/web/conf/nginx/conf.d:/etc/nginx/conf.d
            - ~/web:/web
        #container_name: nginx-host
        networks:
            - frontend
        depends_on:
            - php
    php:
        #image: "${DOCKER_USER}/lnmp-php:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.php
        volumes:
            - ~/web:/web
        networks:
            - frontend
            - backend
        environment:
            MYSQL_PASSWORD: 123456
        depends_on:
            - mysql
            - redis
    mysql:
        image: mysql:5.7
        volumes:
            - ~/web/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: 123456
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
    redis:
        image: redis:3.2
        ports:
            - "6379:6379"
        volumes:
            - ~/web/redis:/data
        networks:
            - backend
volumes:
    mysql-data:

networks:
    frontend:
    backend:
